sudo: required
services:
  - docker

before_install: 
  - docker build -t alp/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run alp/react-test npm test -- --coverage

after_success: 
  - docker build -t alp/multi-client ./client
  - docker build -t alp/multi-nginx ./nginx
  - docker build -t alp/multi-server ./server
  - docker build -t alp/multi-worker ./worker