sudo: required
services:
  - docker

before_install: 
  - docker build -t alexp2023/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true alexp2023/react-test npm test

after_success: 
  - docker build -t alexp2023/multi-client ./client
  - docker build -t alexp2023/multi-nginx ./nginx
  - docker build -t alexp2023/multi-server ./server
  - docker build -t alexp2023/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and poush them to docker hub
  - docker push alexp2023/multi-client
  - docker push alexp2023/multi-nginx
  - docker push alexp2023/multi-server
  - docker push alexp2023/multi-worker